# Generated by Django 2.2.3 on 2019-08-01 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_film', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('films', models.ManyToManyField(to='movie.Film')),
            ],
        ),
        migrations.CreateModel(
            name='Movies_Viewed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Film')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Viewer')),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='viewers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Viewer'),
        ),
    ]
