# Generated by Django 2.2.3 on 2019-08-01 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='viewers',
        ),
    ]
