# Generated by Django 2.2.3 on 2019-08-01 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_remove_film_viewers'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='Viewer',
            field=models.ManyToManyField(to='movie.Viewer'),
        ),
    ]
