# Generated by Django 2.2.3 on 2019-08-01 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_role', models.CharField(max_length=255)),
                ('actor', models.ManyToManyField(to='plays.Actor')),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_play', models.CharField(max_length=255)),
                ('actor', models.ManyToManyField(to='plays.Actor')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plays.Role')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plays.Play')),
            ],
        ),
    ]
