# Generated by Django 2.2.3 on 2019-08-01 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='play',
            name='actor',
        ),
    ]
