# Generated by Django 2.2.3 on 2019-08-01 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0002_remove_play_actor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='play',
            name='role',
        ),
        migrations.AddField(
            model_name='play',
            name='role',
            field=models.ManyToManyField(to='plays.Role'),
        ),
    ]
